function F = fiveratesol(L, j, m, gj, gj1, gj2, gj3, gj4, r)

%Define the parameters that I'm not changing frequently:
N = 1;
%Don't need alpha since it's set to 5 in your lCDF function already

F(1) = gj.*(lCDF(r(1) + L/2) - lCDF(r(1) - L/2)) + ...
    (gj1 - gj).*(lCDF(2.*r(1)) - lCDF(0)) + ...
    (gj2 - gj1).*(lCDF(r(1) + r(2)) - lCDF(r(1) - r(2))) + ...
    (gj3 - gj2).*(lCDF(r(1) + r(3)) - lCDF(r(1) - r(3))) + ...
    (gj4 - gj3).*(lCDF(r(1) + r(4)) - lCDF(r(1) - r(4))) - j*N/m;
    
F(2) = gj.*(lCDF(r(2) + L/2) - lCDF(r(2) - L/2)) + ...
    (gj1 - gj).*(lCDF(r(2) + r(1)) - lCDF(r(2) - r(1))) + ...
    (gj2 - gj1).*(lCDF(2.*r(2)) - lCDF(0)) + ...
    (gj3 - gj2).*(lCDF(r(2) + r(3)) - lCDF(r(2) - r(3))) + ...
    (gj4 - gj3).*(lCDF(r(2) + r(4)) - lCDF(r(2) - r(4))) - (j+1)*N/m;
    
F(3) = gj.*(lCDF(r(3) + L/2) - lCDF(r(3) - L/2)) + ...
    (gj1 - gj).*(lCDF(r(3) + r(1)) - lCDF(r(3) - r(1))) + ...
    (gj2 - gj1).*(lCDF(r(3) + r(2)) - lCDF(r(3) - r(2))) + ...
    (gj3 - gj2).*(lCDF(2.*r(3)) - lCDF(0)) + ...
    (gj4 - gj3).*(lCDF(r(3) + r(4)) - lCDF(r(3) - r(4))) - (j+2)*N/m;

F(4) = gj.*(lCDF(r(4) + L/2) - lCDF(r(4) - L/2)) + ...
    (gj1 - gj).*(lCDF(r(4) + r(1)) - lCDF(r(4) - r(1))) + ...
    (gj2 - gj1).*(lCDF(r(4) + r(2)) - lCDF(r(4) - r(2))) + ...
    (gj3 - gj2).*(lCDF(r(4) + r(3)) - lCDF(r(4) - r(3))) + ...
    (gj4 - gj3).*(lCDF(2.*r(4)) - lCDF(0)) - (j+3)*N/m;
    
end